server:
  # 端口
  port: 9000
spring:
  application:
    # 应用名
    name: akacl-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 116.205.188.28:8848
        namespace: cl-namespace
        group: AKACL_GROUP
    # 网关
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: akacl-system
          uri: lb://akacl-system
          predicates:
            - Path=/api/akacl-system/**
          filters:
            - StripPrefix=1
            - AddRequestParameter=red, blue