server:
  # 端口
  port: 11000
  servlet:
    context-path: /auth
spring:
  application:
    # 应用名
    name: akacl-auth
  cloud:
    nacos:
      discovery:
        server-addr: 116.205.188.28:8848
        namespace: cl-namespace
        group: AKACL_GROUP
